version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_container
  #   environment:
  #     MYSQL_ROOT_PASSWORD:
  #     MYSQL_DATABASE: dictionary
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD:
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  kafka:
    image: docker.io/bitnami/kafka:3.7
    container_name: kafka_container
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

volumes:
  redis_data:
  # mysql_data:
  kafka_data:
    driver: local
